
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8013/health

### slides - forms - externals
GET http://localhost:8021/health

GET http://localhost:8022/health

GET http://localhost:8023/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ auth

GET http://localhost:8000/auth/bypass/1
Accept: application/json

POST http://localhost:8000/auth/login
Accept: application/json
Content-Type: application/json

{
  "admin"
}

GET http://localhost:8000/auth
Accept: application/json
Content-Type: application/json
Cookie: <refresh_token>

GET http://localhost:8000/auth/logout
Accept: application/json
Content-Type: application/json
Cookie: <refresh_token>

# }}}
