# Generate secret key and copy to clipboard
# :redir @* | !openssl rand -base64 32 | tr -d '\n' | xclip -selection clipboard

[default]
ident      = "questions_api-base"
port       = 8000
address    = "0.0.0.0"
origin_url = "http://localhost:8000"
secret_key = ""

migrations_run = false

profile_url   = "http://localhost:8001/api/v1/profile"
user_url      = "http://localhost:8002/api/v1/user"
auth_url      = "http://localhost:8003/api/v1/auth"

fcm_url       = "http://localhost:8005/api/v1/fcm"

question_url  = "http://localhost:8011/api/v1/question"
answer_url    = "http://localhost:8012/api/v1/answer"

slide_url     = "http://localhost:8021/api/v1/slide"
form_url      = "http://localhost:8022/api/v1/slide"
external_url  = "http://localhost:8023/api/v1/external"

resource_url  = "http://localhost:8031/api/v1/resource"
paper_url     = "http://localhost:8032/api/v1/paper"

[default.databases.questions]
url = "postgres://base:base@localhost/base"
